-------------------------  INTERMEDIARIAS ---------------------------------
ALTER DATABASE atento_tests COLLATE SQL_Latin1_General_CP1_CI_AS
GO

CREATE TABLE ANET_COMPANY_AREA (

ID INT NOT NULL IDENTITY(1,1),
COMPANY_AREA VARCHAR(100),
NAME VARCHAR(100),
DESCRIPTION VARCHAR(255),

CONSTRAINT pk_ANET_COMPANY_AREA PRIMARY KEY (ID),

);

GO

CREATE TABLE ANET_COMPANY_HIERACHY (

ID INT NOT NULL IDENTITY(1,1),
COMPANY_HIERACHY VARCHAR(100),
NAME VARCHAR(100),
DESCRIPTION VARCHAR(255),
CONTACT VARCHAR(255),

CONSTRAINT pk_ANET_COMPANY_HIERACHY PRIMARY KEY (ID),

);

GO

CREATE TABLE ANET_PARTICIPANT (

ID INT NOT NULL IDENTITY(1,1),
COMPANY_AREA VARCHAR(100),
COMPANY_HIERACHY VARCHAR(100),
RE VARCHAR(50),
NAME VARCHAR(255),
EMAIL VARCHAR(255),
PASSWORD VARCHAR(50),
ACTIVE BIT,
GENDER CHAR,
FULLBIRTHDAY DATETIME,
CPF VARCHAR(14),
CONTRACT VARCHAR(255),
RE_SUPERIOR VARCHAR(255),
MARITAL_STATUS INT,
SCHOLARITY INT,
COST_CENTER VARCHAR(255),
ADMISSION_DATE DATETIME,
RG VARCHAR(255),
EXECUTIVE_BOARD VARCHAR(255),
CONSULTING_NAME VARCHAR(255),
PHONE VARCHAR(20)

CONSTRAINT pk_ANET_PARTICIPANT PRIMARY KEY (ID),

);

GO

CREATE TABLE ANET_MANAGER_PARTICIPANT (

MANAGER_RE VARCHAR(50) NOT NULL,
PARTICIPANT_RE VARCHAR(50) NOT NULL,

CONSTRAINT pk_ANET_MANAGER_PARTICIPANT PRIMARY KEY (MANAGER_RE, PARTICIPANT_RE),

);

GO

-------------------------  AULANET ---------------------------------
CREATE TABLE [dbo].[EMPRESA_AREA](
	[STR_ID_EA] [varchar](50) NOT NULL,
	[STR_IDPAI_EA] [varchar](50) NULL,
	[STR_NOME_EA] [varchar](100) NOT NULL,
	[STR_DESC_EA] [varchar](255) NULL,
 CONSTRAINT [aaaaaEMPRESA_AREA_PK] PRIMARY KEY NONCLUSTERED 
(
	[STR_ID_EA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[EMPRESA_HIERARQUIA](
	[STR_ID_EH] [varchar](50) NOT NULL,
	[STR_IDPAI_EH] [varchar](50) NULL,
	[STR_NOME_EH] [varchar](100) NOT NULL,
	[STR_DESC_EH] [varchar](255) NULL,
	[STR_ID_EA] [varchar](50) NULL,
	[INFOCONTATO] [varchar](255) NULL,
 CONSTRAINT [aaaaaEMPRESA_HIERARQUIA_PK] PRIMARY KEY NONCLUSTERED 
(
	[STR_ID_EH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Participante](
	[Id] [int] NOT NULL,
	[Nome] [varchar](255) NOT NULL,
	[Email] [varchar](255) NOT NULL,
	[DescricaoProfissional] [text] NULL,
	[STR_ID_EA] [varchar](50) NULL,
	[STR_ID_EH] [varchar](50) NULL,
	[HomePage] [varchar](255) NULL,
	[Identificacao] [varchar](50) NOT NULL,
	[Senha] [varchar](50) NOT NULL,
	[Tipo] [tinyint] NOT NULL,
	[Ativo] [bit] NOT NULL,
	[GERENTE] [int] NULL,
	[SEXO] [varchar](1) NULL,
	[CIDADE] [varchar](255) NULL,
	[Uf] [varchar](2) NULL,
	[DIANASCIMENTO] [varchar](2) NULL,
	[MESNASCIMENTO] [varchar](2) NULL,
	[ANONASCIMENTO] [varchar](4) NULL,
	[CPF] [varchar](14) NULL,
	[OPCIONAL01] [varchar](255) NULL,
	[OPCIONAL02] [varchar](255) NULL,
	[FOTO] [varchar](255) NULL,
	[TELEFONE] [varchar](255) NULL,
	[ESTADOCIVIL] [int] NULL,
	[ENDERECO] [varchar](255) NULL,
	[ESCOLARIDADE] [int] NULL,
	[OPCIONAL03] [varchar](255) NULL,
	[OPCIONAL04] [varchar](255) NULL,
	[NOME_EMPRESA] [varchar](255) NULL,
	[CNPJ] [varchar](255) NULL,
	[DATAADMISSAO] [datetime] NULL,
	[CELULAR] [varchar](255) NULL,
	[RG] [varchar](255) NULL,
	[NOMECONJUGE] [varchar](255) NULL,
	[DATANASCIMENTOCONJUGE] [datetime] NULL,
	[COMPUTADOR] [bit] NULL,
	[SUPERVISAO] [varchar](255) NULL,
	[SUBSETOR] [varchar](255) NULL,
	[SETOR] [varchar](255) NULL,
	[OPCIONAL05] [varchar](255) NULL,
	[OPCIONAL06] [varchar](255) NULL,
	[OPCIONAL07] [varchar](255) NULL,
	[OPCIONAL08] [varchar](255) NULL,
	[OPCIONAL09] [varchar](255) NULL,
	[OPCIONAL10] [varchar](255) NULL,
	[DATAMODIFICACAOSENHA] [datetime] NULL,
	[DATACRIACAO] [datetime] NULL,
	[OPCIONAL11] [varchar](255) NULL,
	[OPCIONAL12] [varchar](255) NULL,
 CONSTRAINT [aaaaaParticipante_PK] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[GerenteParticipante](
	[idParticipante] [int] NOT NULL,
	[idParticipanteSubordinado] [int] NOT NULL,
 CONSTRAINT [pk_gerenteparticipante_id] PRIMARY KEY CLUSTERED 
(
	[idParticipante] ASC,
	[idParticipanteSubordinado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO